### ISSUE TITLE
Docker configuration is causing BIG performance issue

### ISSUE THREAD

**Issue by hekod777** [GoogleChrome/rendertron#109]
If Rendertron is started by npm start, the performance is awesome! It can render pretty much all the sites very fast.

If Rendertron is started as a docker container, it takes MUCH longer to do the rendering.

for example:

`https://whispering-bayou-43373.herokuapp.com/list/mens_outerwear`

docker container version of Rendertron takes 10+ secs

npm start version of Rendertron takes 4 secs

`https://disneycruise.disney.go.com/`

docker container version of Rendertron takes 8.6-10+ secs

npm start version of Rendertron takes 6-7 secs

Something needs to be done to the docker configuration.

## **Steps to reproduce**

- run rendertron locally using `npm start`
- go to `http://localhost:3000/`
- paste the follow line into the input box
`https://whispering-bayou-43373.herokuapp.com/list/mens_outerwear`
- click the render and serialize with web component v1

----

- build rendertron container `docker build -t rendertron . --no-cache=true`
- run rendertron container   `docker run -it -p 8080:8080 --cap-add SYS_ADMIN --name rendertron-container rendertron`
- paste the following line into the input box
`https://whispering-bayou-43373.herokuapp.com/list/mens_outerwear`
- click the render and serialize with web component v1

## **Results**

npm start will give the rendering result in about 5 secs

docker run will give almost a blank page because it could not finish the rendering in 10 secs

## My guess

since the poor performance is due to the long rendering time, my guess is that some of the docker configuration is making headless chrome run slow.

## Updates

last week, I got the testing result as what I stated above after many many tests.

but this week, everything changed as if this is no longer the world I have lived in last week.

1. docker version of rendertron can render pretty much as fast as npm start version for AngularJS apps (GOOD!)

2. npm start version of rendertron is acting like the docker version of rendertron, and can no longer render several of the apps involve Polymer elements (BAD!)

```
https://whispering-bayou-43373.herokuapp.com/list/ladies_outerwear

https://mighty-dawn-10467.herokuapp.com/heroes

https://shop.polymer-project.org/list/ladies_outerwear
```

**Comment by arthurevans** [comment]
@samuelli Are we using the docker instance for rendering wc.org?

**Comment by zacksiri** [comment]
@hekod777 are you running docker on Mac? because that's running inside a VM (xhyve) and it might cause some slow downs.

**Comment by hekod777** [comment]
hmmm....

It's really really weird.

last week, I got the testing result as what I stated in the first post after many many tests.

but this week, everything changed as if this is no longer the world I have lived in the last week.

1. docker version of rendertron can render pretty much as fast as npm start version for AngularJS apps (GOOD!)

2. npm start version of rendertron is acting like the docker version of rendertron, and can no longer render several of my testing polymer2 apps like

**Comment by hekod777** [comment]
The Docker Container is clearly the biggest block on the road to production.

This is the result after trying out docker and non-docker version of rendertron

1. non-docker version (npm start)

Rendertron can easily handle 8 concurrent users by using only 35% of the CPU

about 4.5% CPU usage per user.

2. docker version

Rendertron will crash if the concurrent users are 4 or more when rendering some of our AngularJS pages.

With 3 concurrent users, Rendertron took about 20% of the CPU usage.

almost 7% CPU usage per user.


The Rendertron docker container clearly can have some improvements.

**Comment by hekod777** [comment]
While non-dockerized version can hold 9 concurrent users without any problem. Dockerized rendertron can only hold 4 concurrent users.

When there are only 4 concurrent users, things worked well. once it reached 5 concurrent users all these errors almost pop up instantly.

```
Uncaught exception
Error: not opened
    at WebSocket.send (/app/node_modules/ws/lib/WebSocket.js:355:18)
    at Chrome.enqueueCommand (/app/node_modules/chrome-remote-interface/lib/chrome.js:124:16)
    at /app/node_modules/chrome-remote-interface/lib/chrome.js:86:28
    at new Promise (<anonymous>)
    at Chrome.send (/app/node_modules/chrome-remote-interface/lib/chrome.js:85:16)
    at Object.handler [as evaluate] (/app/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at pageReadyFn (/app/src/renderer.js:170:36)
    at Timeout.setTimeout (/app/src/renderer.js:188:9)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
10 second time budget limit reached.
          Attempted rendering: https://disneycruise.disney.go.com/cruises-destinations/overview/panama-canal/
          Page load event fired: false
          Outstanding network requests: 1
Uncaught exception
Error: not opened
    at WebSocket.send (/app/node_modules/ws/lib/WebSocket.js:355:18)
    at Chrome.enqueueCommand (/app/node_modules/chrome-remote-interface/lib/chrome.js:124:16)
    at /app/node_modules/chrome-remote-interface/lib/chrome.js:86:28
    at new Promise (<anonymous>)
    at Chrome.send (/app/node_modules/chrome-remote-interface/lib/chrome.js:85:16)
    at Object.handler [as evaluate] (/app/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at pageReadyFn (/app/src/renderer.js:170:36)
    at Timeout.setTimeout (/app/src/renderer.js:188:9)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
10 second time budget limit reached.
          Attempted rendering: https://disneycruise.disney.go.com/cruises-destinations/overview/panama-canal/
          Page load event fired: false
          Outstanding network requests: 14

Uncaught exception
Error: not opened
    at WebSocket.send (/app/node_modules/ws/lib/WebSocket.js:355:18)
    at Chrome.enqueueCommand (/app/node_modules/chrome-remote-interface/lib/chrome.js:124:16)
    at /app/node_modules/chrome-remote-interface/lib/chrome.js:86:28
    at new Promise (<anonymous>)
    at Chrome.send (/app/node_modules/chrome-remote-interface/lib/chrome.js:85:16)
    at Object.handler [as evaluate] (/app/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at pageReadyFn (/app/src/renderer.js:170:36)
    at Timeout.setTimeout (/app/src/renderer.js:188:9)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)

10 second time budget limit reached.
          Attempted rendering: https://disneycruise.disney.go.com/ports/castaway-cay/
          Page load event fired: false
          Outstanding network requests: 2

Uncaught exception
Error: not opened
    at WebSocket.send (/app/node_modules/ws/lib/WebSocket.js:355:18)
    at Chrome.enqueueCommand (/app/node_modules/chrome-remote-interface/lib/chrome.js:124:16)
    at /app/node_modules/chrome-remote-interface/lib/chrome.js:86:28
    at new Promise (<anonymous>)
    at Chrome.send (/app/node_modules/chrome-remote-interface/lib/chrome.js:85:16)
    at Object.handler [as evaluate] (/app/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at pageReadyFn (/app/src/renderer.js:170:36)
    at Timeout.setTimeout (/app/src/renderer.js:188:9)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)

Uncaught exception
{ Error: connect ECONNREFUSED 127.0.0.1:46607
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 46607 }

Uncaught exception
{ Error: connect ECONNREFUSED 127.0.0.1:46607
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 46607 }
Detected 6 errors, shutting instance down

Uncaught exception
{ Error: connect ECONNREFUSED 127.0.0.1:46607
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 46607 }
```

I have checked CPU / Memory / Network, I do not think any of those are causing the issue.

There are two types of errors: 

1. `not opened` error

according to my research, this error is caused by rendertron trying to closed a tab in chrome that does not exist (or maybe already closed). This can be one of the areas to work on to improve the stability of rendertron. I have seen this error occasionally in non-dockerized version of rendertron.

2. `ECONNREFUSED` error

I am not quite sure about this error. I do not see this error in non-dockerized version of rendertron. It might not directly relate to the `not opened` error.

3. Maybe both of these errors were caused by chrome being crashed by the 5th concurrent user in the docker container? If so, maybe we can try improve the stability of chrome in the docker container to improve the performance of rendertron.

**Comment by paambaati** [comment]
@hekod777 Recently, a _slightly_ relevant bug was fixed in `64.0.3281.0` - see https://bugs.chromium.org/p/chromium/issues/detail?id=736452

Would you be willing to retest with the new version?

**Comment by hekod777** [comment]
@paambaati Thank you for the info.

After I adding `--shm-size 512m` to run the docker container (default is 64m, I just made it larger), the docker container works fine now (tested in the latest version of rendertron). And with Sam's fix, the 'not opened' error is greatly reduced. I have to say the stability of rendertron is better than never before.

**Comment by hekod777** [comment]
use `--shm-size` flag to run the docker container fixed the problem.

If you are using AWS ECS where `--shm-size` is not supported, you can try to use `--default-shm-size` flag to start docker daemon as a workaround.

**Comment by vladgolubev** [comment]
Also Chrome 64+ supports `--disable-dev-shm-usage` flag
