### ISSUE TITLE
Cannot find module 'semver' when running Rendertron 

### ISSUE THREAD

**Issue by eladr2805** [GoogleChrome/rendertron#140]
I installed
`npm install -g rendertron`
and then
`npm install -g google-chrome `

When try to run Rendertron im getting

`Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\elad\AppData\Roaming\npm\node_modules\rendertron\bin\rendertron:7:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)`

**Comment by samuelli** [comment]
Hi,

This doesn't appear to be a bug with Rendertron. See https://github.com/npm/npm/issues/19036

Also that is not an official Google Chrome NPM package, please refer to the official Chrome website on how to install Chrome.

Thanks,
Sam

**Comment by panzerdp** [comment]
Faced the same problem.
A simple workaround is to install `semver` globally:

```
npm install -g semver
```

**Comment by samuelli** [comment]
Sorry, it seems that I was mistaken. Fixed in #146
