### ISSUE TITLE
rendertron on freebsd

### ISSUE THREAD

**Issue by beyondcreed** [GoogleChrome/rendertron#178]
Hello,

We are trying to run rendertron on FreeBSD 11.1-RELEASE-p8. However when running rendertron or npm run start, the following error appears.

`TypeError: chromeFinder[utils_1.getPlatform(...)] is not a function
    at Launcher.<anonymous> (/root/rendertron/node_modules/chrome-launcher/dist/chrome-launcher.js:139:80)
    at Generator.next (<anonymous>)
    at /root/rendertron/node_modules/chrome-launcher/dist/chrome-launcher.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (/root/rendertron/node_modules/chrome-launcher/dist/chrome-launcher.js:8:12)
    at Launcher.launch (/root/rendertron/node_modules/chrome-launcher/dist/chrome-launcher.js:127:16)
    at Object.<anonymous> (/root/rendertron/node_modules/chrome-launcher/dist/chrome-launcher.js:48:24)
    at Generator.next (<anonymous>)
    at /root/rendertron/node_modules/chrome-launcher/dist/chrome-launcher.js:12:71
    at new Promise (<anonymous>)`

If anyone has any ideas let us know, we will continue to look further. Thanks.

**Comment by samuelli** [comment]
Is Chrome installed?
