### ISSUE TITLE
failed start rendertron locally in ubuntu server

### ISSUE THREAD

**Issue by alikarimii** [GoogleChrome/rendertron#181]
when `npm run start` , get this error

```
Error: The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.
    at Object.linux (/home/uuu/rendertron/node_modules/chrome-launcher/dist/chrome-finder.js:108:15)
    at Launcher.<anonymous> (/home/uuu/rendertron/node_modules/chrome-launcher/dist/chrome-launcher.js:139:80)
    at Generator.next (<anonymous>)
    at /home/uuu/rendertron/node_modules/chrome-launcher/dist/chrome-launcher.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (/home/uuu/rendertron/node_modules/chrome-launcher/dist/chrome-launcher.js:8:12)
    at Launcher.launch (/home/uuu/rendertron/node_modules/chrome-launcher/dist/chrome-launcher.js:127:16)
    at Object.<anonymous> (/home/uuu/rendertron/node_modules/chrome-launcher/dist/chrome-launcher.js:48:24)
    at Generator.next (<anonymous>)
    at /home/uuu/rendertron/node_modules/chrome-launcher/dist/chrome-launcher.js:12:71
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rendertron@1.1.1 start: `node src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rendertron@1.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by AVGP** [comment]
I wasn't able to reproduce this problem. Could you check if CHROME_PATH is set to something specific on your server or try upgrading to the latest version of Rendertron?

Feel free to reopen this issue if the problem persists.
