### ISSUE TITLE
Could not load the default credentials.

### ISSUE THREAD

**Issue by fishmisswater** [GoogleChrome/rendertron#299]
when I run by docker while caching is enabled . I got this:
 <-- GET /render/https://www.baidu.com/
  xxx GET /render/https://www.baidu.com/ 500 0ms -

  Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
      at GoogleAuth.<anonymous> (/opt/rendertron/node_modules/google-auth-library/build/src/auth/googleauth.js:248:31)
      at step (/opt/rendertron/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
      at Object.next (/opt/rendertron/node_modules/google-auth-library/build/src/auth/googleauth.js:28:53)
      at fulfilled (/opt/rendertron/node_modules/google-auth-library/build/src/auth/googleauth.js:19:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by AVGP** [comment]
According to [the readme](https://github.com/GoogleChrome/rendertron#deploying-using-docker) we're not providing a Docker deployment out of the box.

Due to that, I'm not sure where this error is coming from - maybe it uses Google Cloud datastore and that needs to be set up somehow?

**Comment by fishmisswater** [comment]
even if I run it directly，this issue still exit:
```
<-- GET /render/https://www.ozon.ru/
  xxx GET /render/https://www.ozon.ru/ 500 17ms -

  Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
      at GoogleAuth.<anonymous> (/root/js_load/rendertron/node_modules/google-auth-library/build/src/auth/googleauth.js:248:31)
      at step (/root/js_load/rendertron/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
      at Object.next (/root/js_load/rendertron/node_modules/google-auth-library/build/src/auth/googleauth.js:28:53)
      at fulfilled (/root/js_load/rendertron/node_modules/google-auth-library/build/src/auth/googleauth.js:19:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by AVGP** [comment]
You're using the dataStoreCache, which uses Google Cloud's data store as a
backend.

That means you either

   - need to set up a Google Cloud project and follow the link from the
   error message to setup credentials.
   - pull from master and set `cache` to `memory` in `config.json` (create
   that file if it doesn't exist).
   - disable the cache.

**Comment by fishmisswater** [comment]
I see, thank you
