### ISSUE TITLE
Page fail issue not handled

### ISSUE THREAD

**Issue by imShara** [GoogleChrome/rendertron#362]
```
Unhandled rejection
Error: Page crashed!
    at Page._onTargetCrashed (/home/user/rendertron/node_modules/puppeteer/lib/Page.js:216:24)
    at CDPSession.<anonymous> (/home/user/rendertron/node_modules/puppeteer/lib/Page.js:124:56)
    at CDPSession.emit (events.js:321:20)
    at CDPSession._onMessage (/home/user/rendertron/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/home/user/rendertron/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocket.<anonymous> (/home/user/rendertron/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/home/user/rendertron/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:321:20)
    at Receiver.receiverOnMessage (/home/user/rendertron/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:321:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by AVGP** [comment]
Would you have a URL where we can try this out.
Also, sounds like this would be a good first pull request, if you want to contribute a solution :)

**Comment by imShara** [comment]
It's not fails every time. But if page crashes it kills rendertron. Will dig into this then.

But just achieved another problem (I will open another issue)

**Comment by AVGP** [comment]
By disabling the check for HTTP(S) URLs and requesting to serialize "chrome://crash" I am able to reliably reproduce the issue. Thanks for reporting, @imShara
