### ISSUE TITLE
Error: WebSocket is not open: readyState 3 (CLOSED)

### ISSUE THREAD

**Issue by imShara** [GoogleChrome/rendertron#366]
Rendertron is working 24/7 and after some day (1-2) it fails with error
`Error: WebSocket is not open: readyState 3 (CLOSED)`
And browesr won't restart

This bug is [relative to Puppeteer](https://github.com/puppeteer/puppeteer/issues/4428) and it has [workaround](https://github.com/puppeteer/puppeteer/issues/4428#issuecomment-500184469)

```
  Error: WebSocket is not open: readyState 3 (CLOSED)
      at WebSocket.send (/home/user/rendertron/node_modules/ws/lib/websocket.js:329:19)
      at WebSocketTransport.send (/home/user/rendertron/node_modules/puppeteer/lib/WebSocketTransport.js:60:14)
      at Connection._rawSend (/home/user/rendertron/node_modules/puppeteer/lib/Connection.js:86:21)
      at Connection.send (/home/user/rendertron/node_modules/puppeteer/lib/Connection.js:72:21)
      at Browser._createPageInContext (/home/user/rendertron/node_modules/puppeteer/lib/Browser.js:174:47)
      at BrowserContext.newPage (/home/user/rendertron/node_modules/puppeteer/lib/Browser.js:367:26)
      at Browser.newPage (/home/user/rendertron/node_modules/puppeteer/lib/Browser.js:166:33)
      at Browser.<anonymous> (/home/user/rendertron/node_modules/puppeteer/lib/helper.js:112:23)
      at Renderer.serialize (/home/user/rendertron/src/renderer.ts:68:37)
      at Rendertron.handleRenderRequest (/home/user/rendertron/src/rendertron.ts:96:44)
    -- ASYNC --
      at Browser.<anonymous> (/home/user/rendertron/node_modules/puppeteer/lib/helper.js:111:15)
      at Renderer.serialize (/home/user/rendertron/src/renderer.ts:68:37)
      at Rendertron.handleRenderRequest (/home/user/rendertron/src/rendertron.ts:96:44)
      at /home/user/rendertron/node_modules/koa-route/index.js:39:44
      at dispatch (/home/user/rendertron/node_modules/koa-compose/index.js:42:32)
      at /home/user/rendertron/node_modules/koa-route/index.js:43:16
      at dispatch (/home/user/rendertron/node_modules/koa-compose/index.js:42:32)
      at /home/user/rendertron/node_modules/koa-route/index.js:43:16
      at dispatch (/home/user/rendertron/node_modules/koa-compose/index.js:42:32)
      at bodyParser (/home/user/rendertron/node_modules/koa-bodyparser/index.js:86:11)
```

**Comment by AVGP** [comment]
Thanks for reporting this bug!

Would you be interested in trying to add the workaround to Rendertron?
You can look at https://github.com/GoogleChrome/rendertron/blob/master/src/rendertron.ts#L32 to see where we're instantiating the internal puppeteer instance.

**Comment by imShara** [comment]
@AVGP I have made temporary solution but it not ready for commit. Stay tuned

**Comment by abdonrd** [comment]
I have the same issue!

**Comment by abdonrd** [comment]
@AVGP @imShara check this PR https://github.com/GoogleChrome/rendertron/pull/369

**Comment by AVGP** [comment]
Thanks for working on this, @abdonrd - I did leave a comment on the PR :)
