### ISSUE TITLE
TimeoutError: Navigation timeout of 60000 ms exceeded

### ISSUE THREAD

**Issue by maitza** [GoogleChrome/rendertron#421]
Hello,

Anyone maybe had this issue with Rendertron? I constatly getting this error's - self restart help, but it's annoying and still have errors in logs.

Last version from master, docker.

```
2020-05-29T06:51:11.623992326Z   -- ASYNC --
2020-05-29T06:51:11.623995503Z     at Frame.<anonymous> (/rendertron/node_modules/puppeteer/lib/helper.js:111:15)
2020-05-29T06:51:11.623998947Z     at Page.goto (/rendertron/node_modules/puppeteer/lib/Page.js:675:49)
2020-05-29T06:51:11.624002024Z     at Page.<anonymous> (/rendertron/node_modules/puppeteer/lib/helper.js:112:23)
2020-05-29T06:51:11.624005130Z     at Renderer.serialize (/rendertron/build/renderer.js:70:35)
2020-05-29T06:51:11.624008507Z     at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }
2020-05-29T06:51:19.005881296Z { TimeoutError: Navigation timeout of 60000 ms exceeded
```

```
2020-05-29T04:03:22.680354743Z     at Receiver.emit (events.js:198:13)
2020-05-29T04:03:27.204213158Z npm ERR! code ELIFECYCLE
2020-05-29T04:03:27.204456636Z npm ERR! errno 1
2020-05-29T04:03:27.205675044Z npm ERR! rendertron@2.0.1 start: `node build/rendertron.js`
2020-05-29T04:03:27.205716201Z npm ERR! Exit status 1
2020-05-29T04:03:27.205860031Z npm ERR! 
2020-05-29T04:03:27.205916843Z npm ERR! Failed at the rendertron@2.0.1 start script.
2020-05-29T04:03:27.205954697Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-05-29T04:03:27.287104911Z 
2020-05-29T04:03:27.287200768Z npm ERR! A complete log of this run can be found in:
2020-05-29T04:03:27.287280908Z npm ERR!     /root/.npm/_logs/2020-05-29T04_03_27_206Z-debug.log

```

**Comment by maitza** [comment]
I figured it out' it's related to my settings in config.json

```
{
  "timeout": 60000,
  "cache": "memory"
}
```

`2020-05-29T06:51:19.005881296Z { TimeoutError: Navigation timeout of 60000 ms exceeded`

What I shuould do? Increase more timeout? If site can't render int 60sec? Anyway it's a lot I guess?

**Comment by cstodor** [comment]
I'm having the same problem here. The renderer runs fine on localhost, but after  I've installed Rendertron on my server on a subdomain, the app loads, I can enter URLs but once I hit the render button it always times out. 

This is how my config object looks like:

> public static config: Config = {
        cache: null,
        cacheConfig: {
            snapshotDir: path.join(os.tmpdir(), 'rendertron'),
            cacheDurationMinutes: (60 * 24 * 7).toString(),
            cacheMaxEntries: '1000'
        },
        timeout: 60000,
        port: '3000',
        host: '0.0.0.0',
        width: 1000,
        height: 1000,
        headers: {},
        puppeteerArgs: ['--no-sandbox']
    };

Any suggestions?

**Comment by AVGP** [comment]
All I can tell from the logs: The page you try to render takes longer than 60 seconds to finish loading on your server / in Docker.
You can try increasing the timeout or try to find out why the page takes this long in the environment you're running Rendertron in.

**Comment by AVGP** [comment]
As this seems to be related to the environment Rendertron runs in, I'll close this for now. If you have additional questions and/or information for this issue, feel free to comment and/or reopen.

**Comment by Xin-Ru** [comment]
Hi, I have the same problem with TimeoutError. And also have a problem with my server CPU. When rendertron started to render page, my server CPU always went to 100%. Then it returned TimeoutError. 
Our website is made by Vue, and it runs ok on client side. 
I have no clue to find out what cause this Error. 
Anybody has solution for TimeoutError ?

btw here is my website : [https://demo.quickper.com/](url)

**Comment by maitza** [comment]
I had the same issue with CPU - migrated to better machine, helped, don't have now page crashes or rendertron fail (stoping container on npm build). I have now 80000 ms in config, but still, usually on the night when bot is doing pressure, have errors with TimeoutError. No idea how to fix it.

My is in React, also shop.

**Comment by Xin-Ru** [comment]
> 80000

Thanks for reply :)
What are the specifications of your server? I want to give it a try.
