### ISSUE TITLE
Page crashed - rendertron stopped working

### ISSUE THREAD

**Issue by maitza** [GoogleChrome/rendertron#434]
I have issue on rendertron 2.0.1. Very often is crashing with error log like that - after crash rendertron is listening but is not sending any GET requests - I need to recreate docker-compose to start it again.

Anyone know what's going on with it?

```
2020-07-12T18:01:05.279108993Z Unhandled rejection
2020-07-12T18:01:05.279406984Z Error: Page crashed!
2020-07-12T18:01:05.279415219Z     at Page._onTargetCrashed (/rendertron/node_modules/puppeteer/lib/Page.js:216:24)
2020-07-12T18:01:05.279419459Z     at CDPSession.Page.client.on.event (/rendertron/node_modules/puppeteer/lib/Page.js:124:56)
2020-07-12T18:01:05.279423238Z     at CDPSession.emit (events.js:198:13)
2020-07-12T18:01:05.279426774Z     at CDPSession._onMessage (/rendertron/node_modules/puppeteer/lib/Connection.js:200:12)
2020-07-12T18:01:05.279430724Z     at Connection._onMessage (/rendertron/node_modules/puppeteer/lib/Connection.js:112:17)
2020-07-12T18:01:05.279434407Z     at WebSocketTransport._ws.addEventListener.event (/rendertron/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
2020-07-12T18:01:05.279438055Z     at WebSocket.onMessage (/rendertron/node_modules/puppeteer/node_modules/ws/lib/event-target.js:120:16)
2020-07-12T18:01:05.279441845Z     at WebSocket.emit (events.js:198:13)
2020-07-12T18:01:05.279445383Z     at Receiver.receiverOnMessage (/rendertron/node_modules/puppeteer/node_modules/ws/lib/websocket.js:789:20)
2020-07-12T18:01:05.279451615Z     at Receiver.emit (events.js:198:13)
2020-07-12T18:01:08.987175900Z npm ERR! code ELIFECYCLE
2020-07-12T18:01:08.987201481Z npm ERR! errno 1
2020-07-12T18:01:08.993489280Z npm ERR! rendertron@2.0.1 start: `node build/rendertron.js`
2020-07-12T18:01:08.993521776Z npm ERR! Exit status 1
2020-07-12T18:01:08.998052990Z npm ERR! 
2020-07-12T18:01:08.998218849Z npm ERR! Failed at the rendertron@2.0.1 start script.
2020-07-12T18:01:08.998392232Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-07-12T18:01:09.026577769Z 
2020-07-12T18:01:09.026860783Z npm ERR! A complete log of this run can be found in:
2020-07-12T18:01:09.026872657Z npm ERR!     /root/.npm/_logs/2020-07-12T18_01_08_999Z-debug.log
2020-07-12T18:01:11.070900425Z 
2020-07-12T18:01:11.070949481Z > rendertron@2.0.1 start /rendertron
2020-07-12T18:01:11.070955147Z > node build/rendertron.js
2020-07-12T18:01:11.070958944Z 
2020-07-12T18:01:11.759439973Z Listening on port 8080
```

**Comment by AVGP** [comment]
In that case the browser tab crashed.
We're looking into this in #362 and I'll close this as a duplicate - feel free to comment on #362 if you have further information.
Do you happen to have a sample URL for us to try to reproduce, for instance?
